version: '3.1'
services:
  postgres:
    container_name: pgdb
    image: postgres:10.6
    environment:
      - DEBUG=false
      - DB_EXTENSION=plpgsql,pg_trgm
      - POSTGRES_USER=tech
      - POSTGRES_PASSWORD=d0nt4get
      - POSTGRES_DB=assessments
    ports:
      - "5432:5432"
